apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pumba-generic-pipeline
spec:
  params:
  - name: pumba-object
    type: string
    description: location of the pumba micro-service code
  resources:
  - name: source
    type: git
  - name: image
    type: image
  tasks:
  - name: container-build
    taskRef:
      name: container-build-task
    params:
      - name: pumba-object
        value: $(params.pumba-object)
    resources:
      inputs:
      - name: source
        resource: source
      outputs:
      - name: image
        resource: image