apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: validator
    app.kubernetes.io/name: pumba-validator
    app.kubernetes.io/part-of: pumba
    app.kubernetes.io/managed-by: argocd
  name: pumba-validator
  namespace: pumba
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pumba-validator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pumba-validator
    spec:
      containers:
      - image: adihaimsohn/pumba-validator
      # - image: gcr.io/sodium-inverter-285420/pumba-validator:c54b9d745d2e9a8a6a2cc019ea5554a8eef547d7
        name: pumba-validator
        env:
        - name: K8STOKEN
          value: Bearer ba4ca4ae41d33234f50fcd6081019786fe5213f9b8fab0f64267b9637b18278ce6f98206fb956e99356026b82ecd34c0124c46b38565a84038504a6da6bdca45
        - name: K8S_BASE_URL
          value: 'https://51.138.70.243'
        - name: JOB_URL
          value: '/apis/batch/v1/namespaces/pumba/jobs'
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
              memory: "50Mi"
              cpu: "50m"
          limits:
              memory: "250Mi"
              cpu: "250m"
