apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: validator
    app.kubernetes.io/name: pumba-validator
    app.kubernetes.io/part-of: pumba
    app.kubernetes.io/managed-by: argocd
  name: pumba-validator
  namespace: pumba
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app.kubernetes.io/name: pumba-validator