apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/name: pumba-api-gateway
    app.kubernetes.io/part-of: pumba
    app.kubernetes.io/managed-by: argocd
  name: pumba-api-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pumba-api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pumba-api-gateway
    spec:
      containers:
      - name: pumba-api-gateway
        image: gcr.io/sodium-inverter-285420/pumba-api-gateway:8e94435d4771611c40a9a24e3842b8d4ac65b781
        ports:
        - containerPort: 8080
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
        resources:
          requests:
              memory: "50Mi"
              cpu: "50m"
          limits:
              memory: "250Mi"
              cpu: "250m"
