apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pumba-ui
  name: pumba-ui
  namespace: pumba
spec:
  selector:
    matchLabels:
      app: pumba-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pumba-ui
    spec:
      containers:
      - image: gcr.io/feisty-return-300415/pumba-ui:a17ccea
        name: pumba-ui
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
              memory: "50Mi"
              cpu: "50m"
          limits:
              memory: "250Mi"
              cpu: "250m"
