apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: uploader
    app.kubernetes.io/name: pumba-uploader
    app.kubernetes.io/part-of: pumba
  name: pumba-uploader
  namespace: pumba
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app.kubernetes.io/name: pumba-uploader