apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: pumba-uploader-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: git-webhook
      eventSourceName: webhook
      eventName: pumba-upl
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: pumba-uploader-
              spec:
                entrypoint: main
                arguments:
                  parameters:
                    - name: git_sha
                      value: test
                    - name: microservicename
                      value: pumba-uploader
                volumeClaimTemplates:
                - metadata:
                    name: workdir
                  spec:
                    accessModes: [ "ReadWriteOnce" ]
                    resources:
                      requests:
                        storage: 1Gi
                templates:
                - name: main
                  dag:
                    tasks:
                      - name: generic-pumba-wf
                        templateRef:
                          name: generic-pumba-ci
                          template: main
                      - name: pumba-rest-cd
                        templateRef:
                          name: pumba-rest-cd
                          template: main
                        dependencies:
                        - generic-pumba-wf
                volumes:
                  - name: kaniko-secret
                    secret:
                      secretName: regcred
                      items:
                        - key: auth.json
                          path: config.json
                  - name: git-secret
                    secret:
                      secretName: gitcred
                      items:
                        - key: id_rsa
                          path: id_rsa
                        - key: known_hosts
                          path: known_hosts
          parameters:
            - src:
                dependencyName: git-webhook
                dataKey: body.after
              dest: spec.arguments.parameters.0.value