apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: generic-pumba-ci
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: git-checkout
          templateRef:
            name: git-checkout
            template: main
          arguments:
            parameters:
              - name: gitrepo
                value: https://github.com/linux-devops-opensource/{{workflow.parameters.microservicename}}.git
        # - name: npm-test
          # templateRef:
          #   name: npm-test
          #   template: main
        #   dependencies:
        #     - git-checkout
        - name: dockerBuild
          templateRef:
            name: kaniko
            template: main
          dependencies:
            - git-checkout
            # - npm-test