apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: checker
    app.kubernetes.io/name: pumba-checker
    app.kubernetes.io/part-of: pumba
    app.kubernetes.io/managed-by: argocd
  name: pumba-checker
  namespace: pumba
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app.kubernetes.io/name: pumba-checker